name: Build Manager (manual)

on:
  workflow_dispatch:

jobs:
  build-ksuinit:
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-musl
          - target: x86_64-unknown-linux-musl
    uses: ./.github/workflows/build-ksuinit.yml
    with:
      target: ${{ matrix.target }}
    secrets: inherit

  build-lkm:
    uses: ./.github/workflows/build-lkm.yml
    secrets: inherit

  build-ksud:
    needs: [build-lkm, build-ksuinit]
    strategy:
      matrix:
        include:
          - target: aarch64-linux-android
            os: ubuntu-latest
            pack_ksuinit: true
          - target: armv7-linux-androideabi
            os: ubuntu-latest
            pack_ksuinit: false
          - target: x86_64-linux-android
            os: ubuntu-latest
            pack_ksuinit: true
    uses: ./.github/workflows/ksud.yml
    with:
      target: ${{ matrix.target }}
      os: ${{ matrix.os }}
      pack_ksuinit: ${{ matrix.pack_ksuinit }}

  build-manager:
    needs: build-ksud
    strategy:
      matrix:
        include:
          - manager_type: normal
    uses: ./.github/workflows/build-manager-common.yml
    secrets: inherit
    with:
      manager_type: ${{ matrix.manager_type }}
      need_upload: false
